#!/bin/bash -ex

TARGET_GID=$(stat -c "%g" /var/run/docker.sock)

EXISTS=$(cat /etc/group | grep $TARGET_GID | wc -l)

# Create new group using target GID and add nobody user
if [ $EXISTS == "0" ]; then
    groupadd -g $TARGET_GID tempgroup
    usermod -a -G tempgroup jenkins
else
# GID exists, find group name and add
    GROUP=$(getent group $TARGET_GID | cut -d: -f1)
    usermod -a -G $GROUP jenkins
fi

su - jenkins

exec "$@"